version: '3'
services:
  # db:
  #   image: mysql:5.7
  #   # environment:
  #   #   - MYSQL_ROOT_PASSWORD=root
  #   #   - MYSQL_USER=Admin
  #   #   - MYSQL_PASSWORD=test@adm1n
  #   #   - MYSQL_DATABASE=django
  #   env_file:
  #   - ./.env
  #   ports:
  #   - "3308:3306"
  web:
    env_file:
    - ./.env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - ./DirectoryApp:/app
    - /var/run/mysqld:/mysocket
    command: bash -c "python manage.py migrate &&
                      python manage.py collectstatic --noinput &&
                      gunicorn directoryapp.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    # depends_on:
    # - db
    # python check_db.py --service-name mysql --ip db --port 3306 &&
    # python manage.py runserver 0.0.0.0:8000"
                      
